import type { Metadata } from "next";
import { gothamBlack, inter } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gothamBlack.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
